### ISSUE TITLE
ToDo's de documentação pós unidade 2

### ISSUE THREAD

**Issue by l-ricardo** [mdsreq-fga-unb/2023.1-UnBnoFluxo#45]
- [x] Definir princípios e regras de clean code. (fazer check list)
- [x] Definir padrões de deploy
- [x] Ajeitar a fomatacao dos padrões de codficacao, "Do front" falta uma quebra de linha 
- [ ] Adicionar padroes de codificaçao do back
- [x] Adicionar historico de versoes para aba de Padrões de codificação
